# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'windows-2019'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: './*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    modifyOutputPath: false
    zipAfterPublish: false
    arguments: 'MyFunction/MyFunction.csproj  --configuration Release --output ../artifacts/MyFunction'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/artifacts'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/'
    Contents: 'build$(Build.BuildId).zip'
    TargetFolder: '$(System.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
